### ISSUE TITLE
freezing after starting script

### ISSUE THREAD

**Issue by EtieM** [aeeckhou/shallowHRD#11]
Hello,

I have the following error when running shllowHRD script:

/Rscript Tools/shallowHRD/shallowHRD_hg19_1.13_controlfreec_chrX.R /shallow/Results/23D2655750/FREEC/23D2655750_chr.bam_ratio.txt /shallow/Results/23D2655750/shallowHRD/ Tools/shallowHRD/cytoband_adapted_hg19.csv 

======================================================== 
Sample :  23D2655750_chr 
======================================================== 

Fast gathering segments 1... 
Message d'avis :
NAs introduits lors de la conversion automatique 
Find Threshold 1... 
Erreur dans seqlevels[rankSeqlevels(seqlevels)] <- seqlevels : 
  NAs interdits dans les affectations indicées
Appels : makeGRangesFromDataFrame
Erreur dans h(simpleError(msg, call)) : 
  erreur d'ï¿½valuation de l'argument 'x' lors de la sï¿½lection d'une mï¿½thode pour la fonction 'subsetByOverlaps' : objet 'GRanges_object_ratio_file' introuvable
Appels : subsetByOverlaps -> .handleSimpleError -> h

Can you help me?

Thanks

**Comment by aeeckhou** [comment]
Hello,

I can try at least! 

Did you generate your file with controlFREEC ? If so provide me your config file. 
Also can you provide me your ratio file?

Best,
Alexandre

**Comment by EtieM** [comment]
Yes it was generated with ControlFREEC. Here are the files:
[config_WGS.txt](https://github.com/aeeckhou/shallowHRD/files/11958477/config_WGS.txt)
[23D2655750_chr.bam_ratio.txt](https://github.com/aeeckhou/shallowHRD/files/11958479/23D2655750_chr.bam_ratio.txt)

Thanks!

**Comment by aeeckhou** [comment]
Hello,

I think I found the problem ! You have aligned to reference genome with contigs (Un_gl000247, Un_gl000233....), not just 1->22 + X + Y. 

In the Prerequisities you have this:

"IMPORTANT: Please only use chromosomes 1 to 22 (plus the Chromosome Y if you want to) for the alignment step. Additionnal chromosomes (contigs) might introduce errors."

I am mostly sure the freeze comes at the very least from this!

Try realigning your fastqs (or at least delete the contigs in your controlFREEC ratio file) and then rerun the algorithm.

Kepp me posted,
Alexandre Eeckhoutte

**Comment by EtieM** [comment]
Thanks, it works!
