### ISSUE TITLE
where to find the newest shallowHRD_hg38 script?

### ISSUE THREAD

**Issue by carolinehey** [aeeckhou/shallowHRD#14]
Apologies for any potential oversight on my part, but where can I find the latest version of the shallowHRD_hg38 script? Or is only the older version available?

**Comment by aeeckhou** [comment]
Hello,

I have written after I left my previous lab an hg38 version of the script but haven't really tested it thoroughly. I can send it to you by mail but preferably I would advice to align on hg19 and go with the version latest 1.13 available on github just to be safe.

I you want me to send it to you, I am not at my lab currently and don't have the hg38 script on me, I will only be able to send it to you next Tuesday. Tell me if you still want me to send it to you.

Best regards,
Alexandre Eeckhoutte

**Comment by aeeckhou** [comment]
The hg38 script is discussed in another issue here : https://github.com/aeeckhou/shallowHRD/issues/15 .
I am closing this issue.

Best,
Alexandre
