### ISSUE TITLE
shallowHRD_hg19_1.13_QDNAseq_no_chrX.R  zone 21 position inaccuracy

### ISSUE THREAD

**Issue by GGanakin** [aeeckhou/shallowHRD#21]
CTTN  Position: hg38 chr11:70,398,404-70,436,584

**Comment by aeeckhou** [comment]
Hello,

Indeed you are right, I mistakenly took the hg38 position instead of the hg19 position. I will push a correction directly in the main directory by this evening (Paris time). 

Have a nice day, 
Alexandre
