### ISSUE TITLE
Error or typo in the script

### ISSUE THREAD

**Issue by zhqingit** [aeeckhou/shallowHRD#4]
Hi, 

In script "shallowHRD_hg38.R",  it seems you are using (quantile 75 -quantile 25)/2 (line 758) as the filter, but in the paper, it is (quantile 75 + quantile 25)/2. And I am not sure if 124000000 in line 453 is typo. And I wonder if you can write more details about the algorithm, it seems lots of actions after the threshold finding are missed in the paper. Thank you!

Best,
Qing

**Comment by aeeckhou** [comment]
HI Qing,

Thank you for the message and sorry I took so long to answer I completly missed your comment. You are right, the typo is actually in the article, it is (quantile 75 -quantile 25)/2 ! For the line 453 it will not affect the results but one value should be kept indeed, I changed it in the code for the old version for hg38.

For the software, the CNA cut-off based on the diffrence between large segments of the genomic profiles helps to actually merge large then small segments to finally_ smooth the segmentation. If their difference in terms of value are below the CNA cut-off then two segments are considered to be on the same CNA level and are merged. The new version that I'm provided actually is improving those steps but also provide a more robust detection of CNA cut-off.

Thank you for your comment!

Best regards,
Alexandre
