### ISSUE TITLE
Variable error in QDNA_from_bam_no_chrX.R

### ISSUE THREAD

**Issue by DucoG** [aeeckhou/shallowHRD#6]
Hello,

I noticed the following small error while running [`QDNA_from_bam_no_chrX.R`](https://github.com/aeeckhou/shallowHRD/blob/master/QDNAseq_from_bam_no_chrX.R)

Line 50 uses `outputPath` but I think instead `inputPath` would be the correct variable. The error is present only in this file and not in [`QDNA_from_bam_chrX.R`](https://github.com/aeeckhou/shallowHRD/blob/master/QDNAseq_from_bam_chrX.R)

Line 50:
```R=
readCounts <- binReadCounts(bins, bamfiles=paste0(outputPath,"/",NAMEEE,".bam"))
```
should be changed to:
```R=
readCounts <- binReadCounts(bins, bamfiles=paste0(inputPath,"/",NAMEEE,".bam"))
```

Kind regards,
Duco Gaillard

**Comment by aeeckhou** [comment]
Dear Duco,

Sorry for the delayed answer... 
Thank you for spotting the mistake. I corrected this in [QDNA_from_bam_no_chrX.R](https://github.com/aeeckhou/shallowHRD/blob/master/QDNAseq_from_bam_no_chrX.R).

Best regards,
Alexandre Eeckhoutte
