### ISSUE TITLE
 how to use it to detect genome homologous recombination in non-human resequsing data?

### ISSUE THREAD

**Issue by Yixiangzhang1996** [aeeckhou/shallowHRD#8]
how to use it to detect genome homologous recombination in non-human resequsing data?

**Comment by aeeckhou** [comment]
Hello, 

Sorry I do not know much about Homologous Recombination Deficiency outside of human and PDX models and its exact consequences on different organisms genome. I wouldn't be able to help you and shallowHRD was not developed to assess such thing. There seems to be a lot of literature however available, notably for plants, if you want to dive into it! 

Best regards,
Alexandre Eeckhoutte
